/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yunnex_ndkdemo_Hello */

#ifndef _Included_com_yunnex_ndkdemo_Hello
#define _Included_com_yunnex_ndkdemo_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yunnex_ndkdemo_Hello
 * Method:    sayHello
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yunnex_ndkdemo_Hello_sayHello
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_yunnex_ndkdemo_Hello
 * Method:    callStaticVoidMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yunnex_ndkdemo_Hello_callStaticVoidMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_yunnex_ndkdemo_Hello
 * Method:    testJString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yunnex_ndkdemo_Hello_testJString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
